# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160814_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(default=datetime.datetime(2016, 8, 15, 9, 18, 26, 900383, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
